export default [
  {
    login: "cli3267",
    id: 32401445,
    node_id: "MDQ6VXNlcjMyNDAxNDQ1",
    avatar_url: "https://avatars0.githubusercontent.com/u/32401445?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/cli3267",
    html_url: "https://github.com/cli3267",
    followers_url: "https://api.github.com/users/cli3267/followers",
    following_url:
      "https://api.github.com/users/cli3267/following{/other_user}",
    gists_url: "https://api.github.com/users/cli3267/gists{/gist_id}",
    starred_url: "https://api.github.com/users/cli3267/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/cli3267/subscriptions",
    organizations_url: "https://api.github.com/users/cli3267/orgs",
    repos_url: "https://api.github.com/users/cli3267/repos",
    events_url: "https://api.github.com/users/cli3267/events{/privacy}",
    received_events_url: "https://api.github.com/users/cli3267/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "wallis002",
    id: 48067738,
    node_id: "MDQ6VXNlcjQ4MDY3NzM4",
    avatar_url: "https://avatars0.githubusercontent.com/u/48067738?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/wallis002",
    html_url: "https://github.com/wallis002",
    followers_url: "https://api.github.com/users/wallis002/followers",
    following_url:
      "https://api.github.com/users/wallis002/following{/other_user}",
    gists_url: "https://api.github.com/users/wallis002/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/wallis002/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/wallis002/subscriptions",
    organizations_url: "https://api.github.com/users/wallis002/orgs",
    repos_url: "https://api.github.com/users/wallis002/repos",
    events_url: "https://api.github.com/users/wallis002/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/wallis002/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "conniexu444",
    id: 43225884,
    node_id: "MDQ6VXNlcjQzMjI1ODg0",
    avatar_url: "https://avatars3.githubusercontent.com/u/43225884?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/conniexu444",
    html_url: "https://github.com/conniexu444",
    followers_url: "https://api.github.com/users/conniexu444/followers",
    following_url:
      "https://api.github.com/users/conniexu444/following{/other_user}",
    gists_url: "https://api.github.com/users/conniexu444/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/conniexu444/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/conniexu444/subscriptions",
    organizations_url: "https://api.github.com/users/conniexu444/orgs",
    repos_url: "https://api.github.com/users/conniexu444/repos",
    events_url: "https://api.github.com/users/conniexu444/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/conniexu444/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "danpelis",
    id: 37593951,
    node_id: "MDQ6VXNlcjM3NTkzOTUx",
    avatar_url: "https://avatars3.githubusercontent.com/u/37593951?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/danpelis",
    html_url: "https://github.com/danpelis",
    followers_url: "https://api.github.com/users/danpelis/followers",
    following_url:
      "https://api.github.com/users/danpelis/following{/other_user}",
    gists_url: "https://api.github.com/users/danpelis/gists{/gist_id}",
    starred_url: "https://api.github.com/users/danpelis/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/danpelis/subscriptions",
    organizations_url: "https://api.github.com/users/danpelis/orgs",
    repos_url: "https://api.github.com/users/danpelis/repos",
    events_url: "https://api.github.com/users/danpelis/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/danpelis/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "cdepalma141",
    id: 24257211,
    node_id: "MDQ6VXNlcjI0MjU3MjEx",
    avatar_url: "https://avatars2.githubusercontent.com/u/24257211?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/cdepalma141",
    html_url: "https://github.com/cdepalma141",
    followers_url: "https://api.github.com/users/cdepalma141/followers",
    following_url:
      "https://api.github.com/users/cdepalma141/following{/other_user}",
    gists_url: "https://api.github.com/users/cdepalma141/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/cdepalma141/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/cdepalma141/subscriptions",
    organizations_url: "https://api.github.com/users/cdepalma141/orgs",
    repos_url: "https://api.github.com/users/cdepalma141/repos",
    events_url: "https://api.github.com/users/cdepalma141/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/cdepalma141/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "TimDemetriades",
    id: 49992568,
    node_id: "MDQ6VXNlcjQ5OTkyNTY4",
    avatar_url: "https://avatars1.githubusercontent.com/u/49992568?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/TimDemetriades",
    html_url: "https://github.com/TimDemetriades",
    followers_url: "https://api.github.com/users/TimDemetriades/followers",
    following_url:
      "https://api.github.com/users/TimDemetriades/following{/other_user}",
    gists_url: "https://api.github.com/users/TimDemetriades/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/TimDemetriades/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/TimDemetriades/subscriptions",
    organizations_url: "https://api.github.com/users/TimDemetriades/orgs",
    repos_url: "https://api.github.com/users/TimDemetriades/repos",
    events_url: "https://api.github.com/users/TimDemetriades/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/TimDemetriades/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "arana23",
    id: 43584923,
    node_id: "MDQ6VXNlcjQzNTg0OTIz",
    avatar_url: "https://avatars0.githubusercontent.com/u/43584923?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/arana23",
    html_url: "https://github.com/arana23",
    followers_url: "https://api.github.com/users/arana23/followers",
    following_url:
      "https://api.github.com/users/arana23/following{/other_user}",
    gists_url: "https://api.github.com/users/arana23/gists{/gist_id}",
    starred_url: "https://api.github.com/users/arana23/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/arana23/subscriptions",
    organizations_url: "https://api.github.com/users/arana23/orgs",
    repos_url: "https://api.github.com/users/arana23/repos",
    events_url: "https://api.github.com/users/arana23/events{/privacy}",
    received_events_url: "https://api.github.com/users/arana23/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jsmuster",
    id: 42680523,
    node_id: "MDQ6VXNlcjQyNjgwNTIz",
    avatar_url: "https://avatars1.githubusercontent.com/u/42680523?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jsmuster",
    html_url: "https://github.com/jsmuster",
    followers_url: "https://api.github.com/users/jsmuster/followers",
    following_url:
      "https://api.github.com/users/jsmuster/following{/other_user}",
    gists_url: "https://api.github.com/users/jsmuster/gists{/gist_id}",
    starred_url: "https://api.github.com/users/jsmuster/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jsmuster/subscriptions",
    organizations_url: "https://api.github.com/users/jsmuster/orgs",
    repos_url: "https://api.github.com/users/jsmuster/repos",
    events_url: "https://api.github.com/users/jsmuster/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/jsmuster/received_events",
    type: "User",
    site_admin: false,
  },
];
